<?php


class ProductType
{
    const FOOD_AND_GROCERY = 'FOOD_AND_GROCERY';
    const AUTOMOTIVE = 'AUTOMOTIVE';
    const ENTERTAINMENT = 'ENTERTAINMENT';
    const HOME_AND_GARDEN = 'HOME_AND_GARDEN';
    const HOME_APPLIANCE = 'HOME_APPLIANCE';
    const AUCTION_AND_GROUP_BUYING = 'AUCTION_AND_GROUP_BUYING';
    const FLOWERS_AND_GIFTS = 'FLOWERS_AND_GIFTS';
    const COMPUTER_AND_SOFTWARE = 'COMPUTER_AND_SOFTWARE';
    const HEALTH_AND_BEAUTY = 'HEALTH_AND_BEAUTY';
    const SERVICE_FOR_INDIVIDUAL = 'SERVICE_FOR_INDIVIDUAL';
    const SERVICE_FOR_BUSINESS = 'SERVICE_FOR_BUSINESS';
    const SPORTS = 'SPORTS';
    const CLOTHING_AND_ACCESSORIES = 'CLOTHING_AND_ACCESSORIES';
    const TRAVEL = 'TRAVEL';
    const HOME_AUDIO_PHOTO_VIDEO = 'HOME_AUDIO_PHOTO_VIDEO';
    const TELEPHONY = 'TELEPHONY';
}